(defun sweyla519450 ()
  ;;"Theme generated by Sweyla: http://themes.sweyla.com/seed/519450/"
  (interactive)
  (color-theme-install
   '(sweyla519450
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#00DEE4"))))
     (font-lock-constant-face ((t (:foreground "#84FFFF"))))
     (font-lock-builtin-face ((t (:foreground "#B1CEA3"))))
     (font-lock-function-name-face ((t (:foreground "#32FF64"))))
     (font-lock-variable-name-face ((t (:foreground "#52D776"))))
     (font-lock-keyword-face ((t (:foreground "#03F05B"))))
     (font-lock-string-face ((t (:foreground "#3AE48D"))))
     (font-lock-doc-string-face ((t (:foreground "#3AE48D"))))
     (font-lock-type-face ((t (:foreground "#60EDD8"))))
     )))

(provide 'sweyla519450)
