
(defun sweyla990369 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/990369/"
  (interactive)
  (color-theme-install
   '(sweyla990369
     ((background-color . "#000902")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FF7600"))))
     (font-lock-constant-face ((t (:foreground "#56FFC5"))))
     (font-lock-builtin-face ((t (:foreground "#77FF00"))))
     (font-lock-function-name-face ((t (:foreground "#09C36D"))))
     (font-lock-variable-name-face ((t (:foreground "#80FF32"))))
     (font-lock-keyword-face ((t (:foreground "#00FF00"))))
     (font-lock-string-face ((t (:foreground "#47FF00"))))
     (font-lock-doc-string-face ((t (:foreground "#47FF00"))))
     (font-lock-type-face ((t (:foreground "#5B8078"))))
     )))

(provide 'sweyla990369)
