
(defun sweyla834998 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/834998/"
  (interactive)
  (color-theme-install
   '(sweyla834998
     ((background-color . "#010800")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#84F939"))))
     (font-lock-constant-face ((t (:foreground "#64FF00"))))
     (font-lock-builtin-face ((t (:foreground "#E1FF4F"))))
     (font-lock-function-name-face ((t (:foreground "#FFFF94"))))
     (font-lock-variable-name-face ((t (:foreground "#CEC300"))))
     (font-lock-keyword-face ((t (:foreground "#866E1B"))))
     (font-lock-string-face ((t (:foreground "#CAC798"))))
     (font-lock-doc-string-face ((t (:foreground "#CAC798"))))
     (font-lock-type-face ((t (:foreground "#C2FF00"))))
     )))

(provide 'sweyla834998)
