
(defun sweyla825820 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/825820/"
  (interactive)
  (color-theme-install
   '(sweyla825820
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#009B9D"))))
     (font-lock-constant-face ((t (:foreground "#00B9F1"))))
     (font-lock-builtin-face ((t (:foreground "#50A41D"))))
     (font-lock-function-name-face ((t (:foreground "#00C2BE"))))
     (font-lock-variable-name-face ((t (:foreground "#31A69B"))))
     (font-lock-keyword-face ((t (:foreground "#0C1EDF"))))
     (font-lock-string-face ((t (:foreground "#0C0CF9"))))
     (font-lock-doc-string-face ((t (:foreground "#0C0CF9"))))
     (font-lock-type-face ((t (:foreground "#00936E"))))
     )))

(provide 'sweyla825820)
